general:
  s3_regional_buckets: true
project:
  name: quickstart-aws-biotech-blueprint-cdk
  owner: quickstart-eng@amazon.com
  parameters:
    lambda_source_path: lambda_functions/source
    lambda_zip_path: lambda_functions/packages
  regions:
  - us-east-1
tests:
  default:
    parameters:
      AssetParameters7ef22dac3421fb2d25175b3386053dbc5bdc110e87cbd58600263bf70a6324cdArtifactHashF658FD15: 7ef22dac3421fb2d25175b3386053dbc5bdc110e87cbd58600263bf70a6324cd
      AssetParameters7ef22dac3421fb2d25175b3386053dbc5bdc110e87cbd58600263bf70a6324cdS3BucketA00C8555: $[taskcat_autobucket]
      AssetParameters7ef22dac3421fb2d25175b3386053dbc5bdc110e87cbd58600263bf70a6324cdS3VersionKey27C92598: quickstart-aws-biotech-blueprint-cdk/lambda_functions/packages/asset7ef22dac3421fb2d25175b3386053dbc5bdc110e87cbd58600263bf70a6324cd/||lambda.zip
    regions:
    - us-east-1
    template: templates/AwsBiotechBlueprint.template.quickstart.yml
